"""Column widths and thresholds the tabs share."""

COL_WIDTH_CLIENT_ID = 100
COL_WIDTH_ADDRESS = 150
COL_WIDTH_AGE = 80
COL_WIDTH_IDLE = 80
COL_WIDTH_DB = 60
COL_WIDTH_COMMAND = 200
COL_WIDTH_TIMESTAMP = 180
COL_WIDTH_DURATION = 100
COL_WIDTH_SLOWLOG_CMD = 400
STAT_LABEL_WIDTH = 200
