"""ai

Revision ID: 038
Revises: 037
Create Date: 2026-09-24 13:23:52.706251

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "038"
down_revision = "037"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("column", "llm_usage", "duration_ms")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_org_role", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_llm_org_role", ["org_id", "role"])

    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.add_column(sa.Column("duration_ms", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("cache_read_tokens", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("cache_write_tokens", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("tool_calls", sa.Integer(), nullable=True))
        batch_op.create_index(
            "ix_llm_usage_timestamp_model_id", ["timestamp", "model_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_llm_usage_timestamp_model_id")
        batch_op.drop_column("tool_calls")
        batch_op.drop_column("cache_write_tokens")
        batch_op.drop_column("cache_read_tokens")
        batch_op.drop_column("duration_ms")

    with op.batch_alter_table("llm_org_role", schema=None) as batch_op:
        batch_op.drop_constraint("uq_llm_org_role", type_="unique")

    # ### end Alembic commands ###
