"""ai_agents

Revision ID: 039
Revises: 038
Create Date: 2026-09-24 13:23:52.813618

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "039"
down_revision = "038"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "agent_tool_call")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tool_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "turn_id", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column(
            "tool_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("call_index", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("result_bytes", sa.Integer(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("conversation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("agent_tool_call", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_tool_call_agent_slug"), ["agent_slug"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_tool_call_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_agent_tool_call_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_agent_tool_call_name_created", ["tool_name", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_tool_call_turn_id"), ["turn_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_tool_call_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_tool_call", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_tool_call_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_tool_call_turn_id"))
        batch_op.drop_index("ix_agent_tool_call_name_created")
        batch_op.drop_index(batch_op.f("ix_agent_tool_call_created_at"))
        batch_op.drop_index(batch_op.f("ix_agent_tool_call_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_agent_tool_call_agent_slug"))

    op.drop_table("agent_tool_call")
    # ### end Alembic commands ###
