"""scheduler

Revision ID: 040
Revises: 039
Create Date: 2026-09-24 13:23:53.240433

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "040"
down_revision = "039"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "apscheduler_jobs")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("next_run_time", sa.Float(precision=25), nullable=True),
        sa.Column("job_state", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("apscheduler_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apscheduler_jobs_next_run_time"),
            ["next_run_time"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("apscheduler_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apscheduler_jobs_next_run_time"))

    op.drop_table("apscheduler_jobs")
    # ### end Alembic commands ###
