"""ai

Revision ID: 041
Revises: 040
Create Date: 2026-09-24 20:16:03.578483

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "041"
down_revision = "040"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "stt_usage")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stt_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_duration_seconds", sa.Float(), nullable=True),
        sa.Column("input_bytes", sa.Integer(), nullable=True),
        sa.Column("output_characters", sa.Integer(), nullable=True),
        sa.Column(
            "detected_language", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("stt_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stt_usage_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stt_usage_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stt_usage_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "tts_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_characters", sa.Integer(), nullable=True),
        sa.Column("output_duration_seconds", sa.Float(), nullable=True),
        sa.Column("output_bytes", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("tts_usage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tts_usage_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tts_usage_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tts_usage_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tts_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tts_usage_user_id"))
        batch_op.drop_index(batch_op.f("ix_tts_usage_timestamp"))
        batch_op.drop_index(batch_op.f("ix_tts_usage_provider"))

    op.drop_table("tts_usage")
    with op.batch_alter_table("stt_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stt_usage_user_id"))
        batch_op.drop_index(batch_op.f("ix_stt_usage_timestamp"))
        batch_op.drop_index(batch_op.f("ix_stt_usage_provider"))

    op.drop_table("stt_usage")
    # ### end Alembic commands ###
