"""ai_agents

Revision ID: 042
Revises: 041
Create Date: 2026-09-25 15:06:17.628273

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "042"
down_revision = "041"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("column", "agent", "extends")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("extends", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_index(batch_op.f("ix_agent_extends"), ["extends"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_extends"))
        batch_op.drop_column("extends")

    # ### end Alembic commands ###
