"""ai

Revision ID: 043
Revises: 042
Create Date: 2026-09-25 21:27:16.976953

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "043"
down_revision = "042"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "voice_profile")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("stt_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stt_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tts_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tts_model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tts_voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tts_speed", sa.Float(), nullable=False),
        sa.Column(
            "tts_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("reply", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("working_sound", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("voice_profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_voice_profile_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_voice_profile_name"), ["name"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("voice_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_voice_profile_name"))
        batch_op.drop_index(batch_op.f("ix_voice_profile_is_active"))

    op.drop_table("voice_profile")
    # ### end Alembic commands ###
