"""ai

Revision ID: 045
Revises: 044
Create Date: 2026-09-26 15:25:14.528761

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = '045'
down_revision = '044'
branch_labels = None
depends_on = None
aegis_stamp_signature = ('table', 'chat_card')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_card',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    with op.batch_alter_table('chat_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_card_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_card_conversation_id'))

    op.drop_table('chat_card')
    # ### end Alembic commands ###
