"""ai

Revision ID: 046
Revises: 045
Create Date: 2026-09-27 11:54:57.117374

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "046"
down_revision = "045"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("column", "llm_usage", "conversation_id")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "conversation_id",
                sqlmodel.sql.sqltypes.AutoString(length=64),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "session_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
            )
        )
        batch_op.add_column(sa.Column("audio_seconds", sa.Float(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_llm_usage_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_llm_usage_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_usage_session_id"))
        batch_op.drop_index(batch_op.f("ix_llm_usage_conversation_id"))
        batch_op.drop_column("audio_seconds")
        batch_op.drop_column("session_id")
        batch_op.drop_column("conversation_id")

    # ### end Alembic commands ###
