"""finance

Revision ID: 050
Revises: 049
Create Date: 2026-10-01 19:06:51.672427

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "050"
down_revision = "049"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("column", "finance_budget_category", "deleted_at")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finance_budget_category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finance_budget_category", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
