"""finance

Revision ID: 052
Revises: 051
Create Date: 2026-10-02 20:59:00.017461

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "052"
down_revision = "051"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "finance_transaction_link")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finance_transaction_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["finance_transaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("finance_transaction_link", schema=None) as batch_op:
        batch_op.create_index("ix_finance_txnlink_label", ["label"], unique=False)
        batch_op.create_index(
            "uq_finance_txnlink", ["transaction_id", "label"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("finance_transaction_link", schema=None) as batch_op:
        batch_op.drop_index("uq_finance_txnlink")
        batch_op.drop_index("ix_finance_txnlink_label")

    op.drop_table("finance_transaction_link")
    # ### end Alembic commands ###
