"""matters

Revision ID: 053
Revises: 052
Create Date: 2026-10-02 21:17:17.473171

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "053"
down_revision = "052"
branch_labels = None
depends_on = None
aegis_stamp_signature = ("table", "party_relation")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "party_relation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("related_party_id", sa.Integer(), nullable=False),
        sa.Column(
            "relation", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("party_relation", schema=None) as batch_op:
        batch_op.create_index("ix_party_relation_party", ["party_id"], unique=False)
        batch_op.create_index(
            "ix_party_relation_related", ["related_party_id"], unique=False
        )
        batch_op.create_index(
            "uq_party_relation",
            ["party_id", "related_party_id", "relation"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("party_relation", schema=None) as batch_op:
        batch_op.drop_index("uq_party_relation")
        batch_op.drop_index("ix_party_relation_related")
        batch_op.drop_index("ix_party_relation_party")

    op.drop_table("party_relation")
    # ### end Alembic commands ###
