"""Cross-platform port resolution for ``make serve`` / ``uv run poe serve``.

Picks free host ports so a busy default (another stack, a local Postgres on
5432, etc.) doesn't kill the run with "bind: address already in use". Only
the HOST publish is ever shifted; containers keep their fixed internal ports
and reach each other by service name inside the compose network.

Used directly (in-process) by ``scripts/dev_tasks.py``, which both the
Makefile and the ``uv run poe`` tasks call into, so there is exactly one
port-resolution implementation shared by both interfaces.
"""

from __future__ import annotations

import errno
import os
from pathlib import Path
import socket
import sys

_PERSISTED_KEYS = {
    "POSTGRES_HOST_PORT",
    "REDIS_HOST_PORT",
    "OLLAMA_HOST_PORT",
    "INGRESS_DASHBOARD_PORT",
}

_DEFAULT_PORTS_FILE = Path(__file__).resolve().parent.parent / ".env.ports"


def _attempt(port: int) -> int:
    """Probe by connecting rather than binding, so ports below 1024 need no root.

    Returns 0 (free), 1 (busy), or -1 (ambiguous: a self-connect EINVAL
    collision right after a recent bind, seen on macOS; not a real "in use"
    signal, so the caller retries rather than trusting it).
    """
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(1.0)
    try:
        sock.connect(("127.0.0.1", port))
    except ConnectionRefusedError:
        return 0
    except OSError as exc:
        return -1 if exc.errno == errno.EINVAL else 1
    else:
        return 1
    finally:
        sock.close()


def _is_free(port: int) -> bool:
    for _ in range(3):
        verdict = _attempt(port)
        if verdict >= 0:
            return verdict == 0
    return False  # persistent EINVAL: treat as unavailable, don't hand it out


def _find_free_port(start: int, max_attempts: int = 20) -> int:
    for port in range(start, start + max_attempts):
        if _is_free(port):
            return port
    raise RuntimeError(
        f"find_free_port: no free port in {start}..{start + max_attempts - 1}"
    )


def _resolve_one(base: int, label: str, scheme: str = "http://") -> int:
    port = _find_free_port(base)
    if port == base:
        print(f">> {label}: {scheme}127.0.0.1:{port}", file=sys.stderr)
    else:
        print(
            f">> port {base} in use - {label} on {scheme}127.0.0.1:{port}",
            file=sys.stderr,
        )
    return port


def docs_port(base: int | None = None) -> int:
    """The host port ``make docs-serve`` should bind.

    Same rule as every other host publish: take the base if it is free,
    otherwise the next one that is. 8001 was hardcoded, which is exactly
    the port a second stack's webserver resolves to, so previewing docs
    beside a running app failed to bind.
    """
    if base is None:
        base = int(os.environ.get("DOCS_PORT_BASE", "8001"))
    return _resolve_one(base, "docs")


def resolve_ports(
    *,
    ingress: bool,
    postgres: bool,
    redis: bool,
    ollama: bool,
    ports_file: Path | None = None,
) -> dict[str, int]:
    """Resolve host ports for the requested services and persist them.

    Only ``POSTGRES_HOST_PORT``, ``REDIS_HOST_PORT``, ``OLLAMA_HOST_PORT``
    and ``INGRESS_DASHBOARD_PORT`` are written to ``.env.ports``:
    ``app/core/config.py``'s ``Settings`` loads that file as a strict dotenv
    (``extra="forbid"``) with no field for ``WEBSERVER_HOST_PORT`` /
    ``INGRESS_HTTP_PORT`` -- those only need to reach ``docker compose``'s
    environment, which the caller does directly with the returned dict.
    """
    ports: dict[str, int] = {
        "WEBSERVER_HOST_PORT": _resolve_one(
            int(os.environ.get("WEBSERVER_PORT_BASE", "8000")),
            "webserver",
        )
    }
    if ingress:
        ports["INGRESS_HTTP_PORT"] = _resolve_one(
            int(os.environ.get("INGRESS_PORT_BASE", "80")),
            "ingress",
        )
        ports["INGRESS_DASHBOARD_PORT"] = _resolve_one(
            int(os.environ.get("INGRESS_DASHBOARD_BASE", "8080")),
            "traefik dashboard",
        )
    if postgres:
        ports["POSTGRES_HOST_PORT"] = _resolve_one(
            int(os.environ.get("POSTGRES_PORT_BASE", "5432")),
            "postgres",
            "",
        )
    if redis:
        ports["REDIS_HOST_PORT"] = _resolve_one(
            int(os.environ.get("REDIS_PORT_BASE", "6379")),
            "redis",
            "",
        )
    if ollama:
        ports["OLLAMA_HOST_PORT"] = _resolve_one(
            int(os.environ.get("OLLAMA_PORT_BASE", "11434")),
            "ollama",
            "",
        )

    target = ports_file or _DEFAULT_PORTS_FILE
    lines = [
        "# Auto-generated by make serve / uv run poe serve.",
        "# Host publish ports for this run. Ephemeral and gitignored;",
        "# read by app/core/config.py for host-side service URLs.",
    ]
    lines.extend(
        f"{key}={value}" for key, value in ports.items() if key in _PERSISTED_KEYS
    )
    target.write_text("\n".join(lines) + "\n")

    return ports
